In [ ]:
#Statistical Analysis

In [1]:
import pandas as pda
import datetime as dtm
import statsmodels.api as smd
import pandas_datareader.data as pdr

In [3]:
#set period
end_date = dtm.date(2020,11,30)
start_date = dtm.date(end_date.year-1, end_date.month, end_date.day)
print(start_date, end_date)

2019-11-30 2020-11-30

In [20]:
stock_BABA = pda.read_csv("stock_data/BABA.csv")

In [21]:
#stock returns
stock_BABA

,Date,Open,High,Low,Close,Adj Close,Volume
0,2020-01-13,228.809998,231.139999,227.039993,230.479996,230.479996,17544800
1,2020-01-14,230.050003,230.175003,224.880005,226.490005,226.490005,17266900
2,2020-01-15,226.649994,227.820007,224.389999,225.059998,225.059998,10743400
3,2020-01-16,226.300003,226.330002,222.729996,223.940002,223.940002,13700500
4,2020-01-17,225.899994,228.000000,225.350006,227.429993,227.429993,12956200
...,...,...,...,...,...,...,...
247,2021-01-05,229.050003,240.759995,228.119995,240.399994,240.399994,35823800
248,2021-01-06,234.949997,238.300003,225.860001,227.610001,227.610001,37146100
249,2021-01-07,229.309998,229.949997,220.089996,226.899994,226.899994,49361800
250,2021-01-08,227.880005,238.600006,226.682999,236.190002,236.190002,34822500
251,2021-01-11,227.880005,230.539993,228.259995,229.419998,229.419998,3994280

In [51]:
stock_BABA = pda.read_csv("stock_data/BABA.csv",skipinitialspace = True, usecols=['Date','Adj Close'],low_memory= True)
stock_AAPL = pda.read_csv("stock_data/AAPL.csv",skipinitialspace = True, usecols=['Date','Adj Close'],low_memory= True)

In [52]:
stock_BABA

           Date   Adj Close
0    2020-01-13  230.479996
1    2020-01-14  226.490005
2    2020-01-15  225.059998
3    2020-01-16  223.940002
4    2020-01-17  227.429993
..          ...         ...
247  2021-01-05  240.399994
248  2021-01-06  227.610001
249  2021-01-07  226.899994
250  2021-01-08  236.190002
251  2021-01-11  229.419998

[252 rows x 2 columns]

In [53]:
stock_AAPL

           Date   Adj Close
0    2020-01-13   78.561531
1    2020-01-14   77.500702
2    2020-01-15   77.168564
3    2020-01-16   78.135223
4    2020-01-17   79.000244
..          ...         ...
247  2021-01-05  131.009995
248  2021-01-06  126.599998
249  2021-01-07  130.919998
250  2021-01-08  132.050003
251  2021-01-11  128.910004

[252 rows x 2 columns]

In [56]:
stock_BABA = pda.read_csv("stock_data/BABA.csv",index_col='Date',parse_dates=['Date'], usecols=['Date','Adj Close'])
stock_AAPL = pda.read_csv("stock_data/AAPL.csv",index_col='Date',parse_dates=['Date'], usecols=['Date','Adj Close'])

In [57]:
stockret_mon = stock_BABA.resample('M').agg(lambda X: (X+1).prod()-1)
AAPL_stockret_mon = stock_AAPL.resample('M').agg(lambda X: (X+1).prod()-1)
stockret_mon

               Adj Close
Date
2020-01-31  5.828498e+32
2020-02-29  2.381556e+44
2020-03-31  2.163952e+50
2020-04-30  2.772696e+48
2020-05-31  1.497687e+46
2020-06-30  3.529779e+51
2020-07-31  5.110768e+52
2020-08-31  8.511986e+50
2020-09-30  2.181503e+51
2020-10-31  4.184009e+54
2020-11-30  6.310427e+48
2020-12-31  9.049230e+52
2021-01-31  1.573056e+14

In [58]:
AAPL_stockret_mon

               Adj Close
Date
2020-01-31  3.987391e+26
2020-02-29  9.301488e+35
2020-03-31  1.062256e+40
2020-04-30  3.620046e+38
2020-05-31  7.203436e+37
2020-06-30  4.757426e+42
2020-07-31  4.247039e+43
2020-08-31  3.166281e+43
2020-09-30  2.152515e+43
2020-10-31  3.262041e+45
2020-11-30  2.624247e+41
2020-12-31  2.365821e+46
2021-01-31  5.008833e+12

In [33]:
#set stock_list
stockret_mon.shape

(13, 1)

Fama French¶

𝑟=𝑅𝑓+𝑏𝑚⋅MER+𝑏𝑠⋅SMB+𝑏𝑣⋅HML+𝑏𝑝⋅RMW+𝑏𝑖⋅CMA

𝑟  is expected portfolio return
𝑏𝑚 ,  𝑏𝑠 ,  𝑏𝑣 ,  𝑏𝑝 ,  𝑏𝑖  are factor sensitivities

Factors Analysis
MER  is excess return of a broad market over the risk-free rate ( 𝑅𝑚−𝑅𝑓 )(market factor)

SMB  is the average return on the small stock portfolios minus big stock portfolios (size factor)

HML  is the average return on high book value portfolios minus low book value (value factor)

RMW  is the average return on robust minus weak operating profitability portfolios (profitability factor)

CMA  Conservative minus aggresive investments, proxied by the y/y growth in company asset value (investment factor)

In [6]:
#read the stock data
ff_factors = pdr.DataReader('F-F_Research_Data_5_Factors_2x3','famafrench', start_date, end_date)[0]
ff_factors

         Mkt-RF   SMB    HML   RMW   CMA    RF
Date
2019-11    3.87  0.50  -1.87 -1.58 -1.24  0.12
2019-12    2.77  0.96   1.93  0.09  1.29  0.14
2020-01   -0.11 -4.41  -6.30 -1.36 -2.34  0.13
2020-02   -8.13 -0.04  -3.96 -1.61 -2.49  0.12
2020-03  -13.38 -8.40 -14.11 -1.38  1.21  0.12
2020-04   13.65  2.79  -1.35  2.51 -1.03  0.00
2020-05    5.58  1.92  -4.95  0.71 -3.28  0.01
2020-06    2.46  1.94  -2.22  0.03  0.34  0.01
2020-07    5.77 -3.03  -1.31  0.55  1.06  0.01
2020-08    7.63 -0.94  -2.95  4.27 -1.44  0.01
2020-09   -3.63  0.07  -2.56 -1.15 -1.77  0.01
2020-10   -2.10  4.76   3.88 -0.60 -0.53  0.01
2020-11   12.47  6.75   2.19 -2.78  1.05  0.01

In [59]:
AAPL_stockret_mon.shape

(13, 1)

In [36]:
stockret_mon.shape

(13, 1)

In [37]:
ff_factors.shape

(13, 6)

In [60]:
stockret_mon.index = ff_factors.index
AAPL_stockret_mon.index = ff_factors.index

In [49]:
stockret_mon

            Adj Close
Date
2019-11  5.828498e+32
2019-12  2.381556e+44
2020-01  2.163952e+50
2020-02  2.772696e+48
2020-03  1.497687e+46
2020-04  3.529779e+51
2020-05  5.110768e+52
2020-06  8.511986e+50
2020-07  2.181503e+51
2020-08  4.184009e+54
2020-09  6.310427e+48
2020-10  9.049230e+52
2020-11  1.573056e+14

In [42]:
BABA_data_on_ff =pda.merge(stockret_mon, ff_factors, on='Date')

In [61]:
BABA_data_on_ff

            Adj Close  Mkt-RF     SMB     HML     RMW     CMA      RF
Date
2019-11  5.828498e+32  0.0387  0.0050 -0.0187 -0.0158 -0.0124  0.0012
2019-12  2.381556e+44  0.0277  0.0096  0.0193  0.0009  0.0129  0.0014
2020-01  2.163952e+50 -0.0011 -0.0441 -0.0630 -0.0136 -0.0234  0.0013
2020-02  2.772696e+48 -0.0813 -0.0004 -0.0396 -0.0161 -0.0249  0.0012
2020-03  1.497687e+46 -0.1338 -0.0840 -0.1411 -0.0138  0.0121  0.0012
2020-04  3.529779e+51  0.1365  0.0279 -0.0135  0.0251 -0.0103  0.0000
2020-05  5.110768e+52  0.0558  0.0192 -0.0495  0.0071 -0.0328  0.0001
2020-06  8.511986e+50  0.0246  0.0194 -0.0222  0.0003  0.0034  0.0001
2020-07  2.181503e+51  0.0577 -0.0303 -0.0131  0.0055  0.0106  0.0001
2020-08  4.184009e+54  0.0763 -0.0094 -0.0295  0.0427 -0.0144  0.0001
2020-09  6.310427e+48 -0.0363  0.0007 -0.0256 -0.0115 -0.0177  0.0001
2020-10  9.049230e+52 -0.0210  0.0476  0.0388 -0.0060 -0.0053  0.0001
2020-11  1.573056e+14  0.1247  0.0675  0.0219 -0.0278  0.0105  0.0001

In [62]:
BABA_data_on_ff[['Mkt-RF','SMB','HML','RMW','CMA','RF']] = BABA_data_on_ff[['Mkt-RF','SMB','HML','RMW','CMA','RF']]/100

In [63]:
BABA_data_on_ff

,Adj Close,Mkt-RF,SMB,HML,RMW,CMA,RF
Date,,,,,,,
2019-11,5.828498e+32,0.000387,0.000050,-0.000187,-0.000158,-0.000124,0.000012
2019-12,2.381556e+44,0.000277,0.000096,0.000193,0.000009,0.000129,0.000014
2020-01,2.163952e+50,-0.000011,-0.000441,-0.000630,-0.000136,-0.000234,0.000013
2020-02,2.772696e+48,-0.000813,-0.000004,-0.000396,-0.000161,-0.000249,0.000012
2020-03,1.497687e+46,-0.001338,-0.000840,-0.001411,-0.000138,0.000121,0.000012
2020-04,3.529779e+51,0.001365,0.000279,-0.000135,0.000251,-0.000103,0.000000
2020-05,5.110768e+52,0.000558,0.000192,-0.000495,0.000071,-0.000328,0.000001
2020-06,8.511986e+50,0.000246,0.000194,-0.000222,0.000003,0.000034,0.000001
2020-07,2.181503e+51,0.000577,-0.000303,-0.000131,0.000055,0.000106,0.000001
2020-08,4.184009e+54,0.000763,-0.000094,-0.000295,0.000427,-0.000144,0.000001
2020-09,6.310427e+48,-0.000363,0.000007,-0.000256,-0.000115,-0.000177,0.000001
2020-10,9.049230e+52,-0.000210,0.000476,0.000388,-0.000060,-0.000053,0.000001
2020-11,1.573056e+14,0.001247,0.000675,0.000219,-0.000278,0.000105,0.000001

In [64]:
X=BABA_data_on_ff[['Mkt-RF','SMB','HML','RMW','CMA']]
y=BABA_data_on_ff['Adj Close']

X_sm = smd.add_constant(X)

In [46]:
model = smd.OLS(y,X_sm)
results = model.fit()
results.summary()

C:\Users\Reegan\Anaconda3\envs\dsenv\lib\site-packages\scipy\stats\stats.py:1603: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=13
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              Adj Close   R-squared:                       0.511
Model:                            OLS   Adj. R-squared:                  0.162
Method:                 Least Squares   F-statistic:                     1.463
Date:                Wed, 13 Jan 2021   Prob (F-statistic):              0.312
Time:                        23:35:34   Log-Likelihood:                -1631.6
No. Observations:                  13   AIC:                             3275.
Df Residuals:                       7   BIC:                             3279.
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.513e+53   4.87e+53      0.927      0.385      -7e+53     1.6e+54
Mkt-RF     -1.454e+54   6.12e+54     -0.237      0.819   -1.59e+55     1.3e+55
SMB        -1.445e+54   1.67e+55     -0.086      0.934    -4.1e+55    3.81e+55
HML         1.128e+54   1.35e+55      0.083      0.936   -3.08e+55    3.31e+55
RMW         4.505e+55   2.01e+55      2.244      0.060   -2.42e+54    9.25e+55
CMA        -3.412e+54   2.16e+55     -0.158      0.879   -5.44e+55    4.76e+55
==============================================================================
Omnibus:                        4.429   Durbin-Watson:                   1.875
Prob(Omnibus):                  0.109   Jarque-Bera (JB):                1.748
Skew:                           0.807   Prob(JB):                        0.417
Kurtosis:                       3.788   Cond. No.                         90.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [72]:
import matplotlib.pyplot as plt 
import numpy as np 
  
# plotting the original values 
x = BABA_data_on_ff['x'].tolist() 
y = BABA_data_on_ff['y'].tolist() 
plt.scatter(x, y) 
  
# finding the maximum and minimum 
# values of x, to get the 
# range of data 
max_x = stockret_mon['Date'].max() 
min_x = stockret_mon['Adj Close'].min() 
  
# range of values for plotting 
# the regression line 
x = np.arange(min_x, max_x, 1) 
  
# the substituted equation 
y = 1.0143 * x - 0.4618
  
# plotting the regression line 
plt.plot(y, 'r') 
plt.show()

KeyError: 'x'

In [66]:
AAPL_data =pda.merge(AAPL_stockret_mon, ff_factors, on='Date')
AAPL_data[['Mkt-RF','SMB','HML','RMW','CMA','RF']] = AAPL_data[['Mkt-RF','SMB','HML','RMW','CMA','RF']]/100
X=AAPL_data[['Mkt-RF','SMB','HML','RMW','CMA']]
y=AAPL_data['Adj Close']

X_sm = smd.add_constant(X)

AAPL_data

            Adj Close  Mkt-RF     SMB     HML     RMW     CMA      RF
Date
2019-11  3.987391e+26  0.0387  0.0050 -0.0187 -0.0158 -0.0124  0.0012
2019-12  9.301488e+35  0.0277  0.0096  0.0193  0.0009  0.0129  0.0014
2020-01  1.062256e+40 -0.0011 -0.0441 -0.0630 -0.0136 -0.0234  0.0013
2020-02  3.620046e+38 -0.0813 -0.0004 -0.0396 -0.0161 -0.0249  0.0012
2020-03  7.203436e+37 -0.1338 -0.0840 -0.1411 -0.0138  0.0121  0.0012
2020-04  4.757426e+42  0.1365  0.0279 -0.0135  0.0251 -0.0103  0.0000
2020-05  4.247039e+43  0.0558  0.0192 -0.0495  0.0071 -0.0328  0.0001
2020-06  3.166281e+43  0.0246  0.0194 -0.0222  0.0003  0.0034  0.0001
2020-07  2.152515e+43  0.0577 -0.0303 -0.0131  0.0055  0.0106  0.0001
2020-08  3.262041e+45  0.0763 -0.0094 -0.0295  0.0427 -0.0144  0.0001
2020-09  2.624247e+41 -0.0363  0.0007 -0.0256 -0.0115 -0.0177  0.0001
2020-10  2.365821e+46 -0.0210  0.0476  0.0388 -0.0060 -0.0053  0.0001
2020-11  5.008833e+12  0.1247  0.0675  0.0219 -0.0278  0.0105  0.0001

In [67]:
model = smd.OLS(y,X_sm)
results = model.fit()
results.summary()

C:\Users\Reegan\Anaconda3\envs\dsenv\lib\site-packages\scipy\stats\stats.py:1603: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=13
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              Adj Close   R-squared:                       0.498
Model:                            OLS   Adj. R-squared:                  0.140
Method:                 Least Squares   F-statistic:                     1.392
Date:                Thu, 14 Jan 2021   Prob (F-statistic):              0.333
Time:                        00:04:41   Log-Likelihood:                -1384.9
No. Observations:                  13   AIC:                             2782.
Df Residuals:                       7   BIC:                             2785.
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.963e+45   2.79e+45      2.138      0.070   -6.33e+44    1.26e+46
Mkt-RF     -7.271e+46   3.51e+46     -2.073      0.077   -1.56e+47    1.02e+46
SMB         6.025e+46   9.58e+46      0.629      0.549   -1.66e+47    2.87e+47
HML         8.539e+46   7.74e+46      1.103      0.306   -9.76e+46    2.68e+47
RMW         1.294e+47   1.15e+47      1.125      0.298   -1.43e+47    4.01e+47
CMA         1.154e+46   1.24e+47      0.093      0.928   -2.81e+47    3.04e+47
==============================================================================
Omnibus:                        2.898   Durbin-Watson:                   2.936
Prob(Omnibus):                  0.235   Jarque-Bera (JB):                0.976
Skew:                           0.625   Prob(JB):                        0.614
Kurtosis:                       3.489   Cond. No.                         90.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""